[project]
name = "4-fastapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.128.1",
    "pydantic>=2.12.5",
    "uvicorn>=0.40.0",
    "vllm>=0.15.1",
]
